### PR TITLE
This will display info about rejected images in the images view

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by jdswinbank** [comment]
It looks like this pull includes a bunch of commits by Tim from several months ago, and I don't really understand why. What's going on?

**Comment by gijzelaerr** [comment]
I think I mixed up some pulls and merges between the several repo's. But effectively nothing changed, so I thought it wasn't a biggy.

**Comment by jdswinbank** [comment]
I like clean history, so I repackaged the relevant commits into a new pull request at https://github.com/transientskp/TKP-web/pull/3. Are you happy with me merging that instead?

**Comment by gijzelaerr** [comment]
sure!

**Pull request closed without merging**
