### PR TITLE
Fix legend color problem

### PR DESCRIPTION
**Pull request by gijzelaerr**
This should fix issue #4228

https://support.astron.nl/lofar_issuetracker/issues/4228

### CODE REVIEW

**Comment by jdswinbank** [comment]
Unfortunately the issue tracker is currently down, so I can't write this there. But:

I merged this code, and, sadly, it doesn't seem to be working. Consider eg database `precycle0` on page http://archive.transientskp.org/dataset/131/transient/52971/. The key lists the same frequency (128.6 MHz) 10 different times, which is obviously no good.

I suspect (without actually checking) that there's a rounding issue here -- the different colours may well correspond to different frequencies which are all being rounded to 128.6 MHz for display. That's understandable, but not adequate -- we'll need a smarter way to handle this.

**Comment by jdswinbank** [comment]
Hmm, actually, it seems to be more nuanced than that.

The plot seems to accurately reflect the contents of the database. However, the database appears to contain a lot of identical entries in the `frequencyband` table:

```
sql>select * from frequencyband where id > 180;
+------+--------------------------+--------------------------+--------------------------+
| id   | freq_central             | freq_low                 | freq_high                |
+======+==========================+==========================+==========================+
|  181 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  182 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  183 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  184 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  185 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  186 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  187 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  188 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  189 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  190 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  191 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|  192 |             128613281.25 |         127642822.265625 |         129583740.234375 |
+------+--------------------------+--------------------------+--------------------------+
```

Each of these bands is then resulting in a separate entry on the plot key.

**Comment by gijzelaerr** [comment]
interesting. Bart? :)

**Comment by jdswinbank** [comment]
Looks like this is a mistake in the SQL function `getBand()`. I'll add it to the issue tracker when that reappears.

Basically, `getBand()` checks if an existing frequency band, defined by the combination of a bandwidth and an "effective" frequency already exists, and, if not, it creates a new band when the relevant image is inserted.

This check is performed by checking if there is one (and only one) existing band which has a lower frequency lower than the image being inserted and a higher frequency higher than the image being inserted. If so, that band is returned; if not, a new band is created.

In the precycle0 database, it so happens that there _two_ bands which satisfy this criterion for the data being inserted:

```
sql>select * from frequencyband where freq_low <= 127642822.265625 and freq_high >= 129583740.234375 and id <= 30;
+------+--------------------------+--------------------------+--------------------------+
| id   | freq_central             | freq_low                 | freq_high                |
+======+==========================+==========================+==========================+
|   25 |             128613281.25 |         127642822.265625 |         129583740.234375 |
|   30 |       131639099.12100001 |       123728942.87100001 |       139549255.37099999 |
+------+--------------------------+--------------------------+--------------------------+
```

In this case, the check for "one and only one" always fails, so every time `getBand()` is called, a new band is created:

```
sql>SELECT getBand(128613281.25, 1940917.96875);
+----------------------+
| getband_single_value |
+======================+
|                  200 |
+----------------------+
1 tuple (20.573ms)
sql>SELECT getBand(128613281.25, 1940917.96875);
+----------------------+
| getband_single_value |
+======================+
|                  201 |
+----------------------+
1 tuple (12.183ms)
sql>SELECT getBand(128613281.25, 1940917.96875);
+----------------------+
| getband_single_value |
+======================+
|                  202 |
+----------------------+
1 tuple (13.917ms)
```

The immediate fix is to change from "one and only one" to "at least one", but I'm not sure if that's actually a good solution: in the case given, does the image I'm inserting belong to band 25 or to band 30?

In fact, I think the design of this table is problematic. We identify bands at the _image_ level by the combination of effective frequency & bandwidth, but at the _database_ level by the combination of min, central and max frequencies. I think that's doomed to failure: you can never be sure you're going to come up with an unambiguous mapping.

**Comment by jdswinbank** [comment]
See https://github.com/transientskp/tkp/pull/152

**Pull request merged**
